### ISSUE TITLE
Down the White Nile card implementations

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3025]
Implementation status of data pack cards.
If you wish to claim a card before working on it, mark up the text below or add a comment to the issue.

- [x] Acacia (#2933)
- [x] Plague (#3028)
- [x] Credit Kiting (#3029)
- [x] Wari (#3046)
- [x] Kabonesa Wu: Netspace Thrillseeker (#3032)
- [x] Takobi (#3040)
- [x] Kongamato (#3038)
- [x] Emergent Creativity (#3047)
- [x] RNG Key (#3043)
- [x] Nightdancer (#3033)
- [x] Jinja City Grid (#3024)
- [x] Aimor (#3031)
- [x] Bacterial Programming (#3053)
- [x] Jua (#3042)
- [x] Threat Assessment (#3037)
- [x] Economic Warfare (#3019)
- [x] Forced Connection (#3036)
- [x] SSL Endorsement (#3023)
- [x] NGO Front (#3027)
- [x] Distract the Masses (#3052 )

**Comment by butzopower** [comment]
@jwarwick I can have a try at NGO Front.

**Comment by butzopower** [comment]
I'll try Plague next @jwarwick

**Comment by butzopower** [comment]
Can do Credit Kiting too.

**Comment by presheaf** [comment]
I'll start out with Kabonesa.

**Comment by presheaf** [comment]
I'll start on Wari now.
