### ISSUE TITLE
Council of the Crest card implementations

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3096]
Rumored to be coming March 1st.

- [x] eXer (#2932)
- [x] Friday Chip (#3107)
- [x] Crypt (#3134)
- [x] Corporate "Grant" (#3097)
- [x] No One Home (#3148)
- [x] Marathon (#3158)
- [x] Gbahali (#3137)
- [x] White Hat (#3133)
- [x] Kuwinda K4H1U3 (#3129)
- [x] NEXT Sapphire (#3132)
- [x] Anansi (#3139 )
- [x] Code Replicator (#3138)
- [x] Reverse Infection (#3128)
- [x] Azmari EdTech: Shaping the Future (#2933)
- [x] Degree Mill (#3141)
- [x] Personalized Portal (#3098)
- [x] Armed Intimidation (#3127)
- [x] Death and Taxes (#3127)
- [x] Trojan Horse (#3157)
- [x] TechnoCo (#3126)

**Comment by Saintis** [comment]
More cards [here](https://www.reddit.com/r/Netrunner/comments/7zdihf/data_breach_textonly_spoilers_of_the_remaining/).

**Comment by butzopower** [comment]
I can do TechnoCo.

**Comment by presheaf** [comment]
I can do Marathon.

**Comment by jwarwick** [comment]
All card implementations merged.
