### ISSUE TITLE
Reign and Reverie Cards

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#3184]
Checked off means that the card has a PR submitted.
Place a link to the pull request next to the card when it is pushed.
If you wish to claim a card, make a comment on this issue or put your name next to the card.

- [x] [Nathaniel \"Gnat\" Hall](https://netrunnerdb.com/en/card/22001) (#3682)
- [x] [Divide And Conquer](https://netrunnerdb.com/en/card/22002) (#3697)
- [x] [Guinea Pig](https://netrunnerdb.com/en/card/22003) (#3682)
- [x] [Patchwork](https://netrunnerdb.com/en/card/22004) (#3695)
- [x] [Hijacked Router](https://netrunnerdb.com/en/card/22005) (#3679)
- [x] [Cradle](https://netrunnerdb.com/en/card/22006) (#3656)
- [x] [District 99](https://netrunnerdb.com/en/card/22007) (@nicohasa)
- [x] [Liza Talking Thunder](https://netrunnerdb.com/en/card/22008) (#3681)
- [x] [Hot Pursuit](https://netrunnerdb.com/en/card/22009) (#3681)
- [x] [Paragon](https://netrunnerdb.com/en/card/22010) (#3681)
- [x] [Bankroll](https://netrunnerdb.com/en/card/220011) (#3681)
- [x] [Tycoon](https://netrunnerdb.com/en/card/22012) (#3657)
- [x] [Thunder Art Gallery](https://netrunnerdb.com/en/card/22013) (#3723)
- [x] [Miss Bones](https://netrunnerdb.com/en/card/22014) (#3702)
- [x] [Akiko Nisei](https://netrunnerdb.com/en/card/22015) (#3299)
- [x] [Insight](https://netrunnerdb.com/en/card/22016) (#3660)
- [x] [Mind's Eye](https://netrunnerdb.com/en/card/22017) (#3703)
- [x] [Mache](https://netrunnerdb.com/en/card/22018) (#3658)
- [x] [Ika](https://netrunnerdb.com/en/card/22019) (#3716)
- [x] [Kyuban](https://netrunnerdb.com/en/card/22020) (#3704)
- [x] [Psych Mike](https://netrunnerdb.com/en/card/22021) (#3713)
- [x] [Algernon](https://netrunnerdb.com/en/card/22022) (#3685)
- [x] [Reboot](https://netrunnerdb.com/en/card/22023) (#3690)
- [x] [Office Supplies](https://netrunnerdb.com/en/card/22024) (#3689)
- [x] [DJ Fenris](https://netrunnerdb.com/en/card/22025) (#3185)
- [x] [Sportsmetal: Go Big or Go Home](https://netrunnerdb.com/en/card/22026) (#3676)
- [x] [Hyperloop Extension](https://netrunnerdb.com/en/card/22027) (#3675)
- [x] [Meridian](https://netrunnerdb.com/en/card/22028) (#3674)
- [x] [Gatekeeper](https://netrunnerdb.com/en/card/22029) (#3719)
- [x] [Divert Power](https://netrunnerdb.com/en/card/22030) (#3683)
- [x] [Fast Break](https://netrunnerdb.com/en/card/22031) (#3730)
- [x] [Game Changer](https://netrunnerdb.com/en/card/22032) (#3688)
- [x] [Giordano Memorial Field](https://netrunnerdb.com/en/card/22033) (#3720)
- [x] [Saraswati Mnemonics: Endless Exploration](https://netrunnerdb.com/en/card/22034) (#3691)
- [x] [Jumon](https://netrunnerdb.com/en/card/22035) (#3710)
- [x] [API-S Keeper Isobel](https://netrunnerdb.com/en/card/22036) (#3668)
- [x] [Neurostasis](https://netrunnerdb.com/en/card/22037) (#3711)
- [x] [Otoroshi](https://netrunnerdb.com/en/card/22038) (#3733)
- [x] [Thimblerig](https://netrunnerdb.com/en/card/22039) (#3738)
- [x] [Hangeki](https://netrunnerdb.com/en/card/22040) (#3733)
- [x] [Daruma](https://netrunnerdb.com/en/card/22041)
- [x] [Acme Consulting: The Truth You Need](https://netrunnerdb.com/en/card/22042) (@msbeck)
- [x] [Fly On The Wall](https://netrunnerdb.com/en/card/22043) (#3673)
- [x] [SIU](https://netrunnerdb.com/en/card/22044) (#3742)
- [x] [Peeping Tom](https://netrunnerdb.com/en/card/22045) (#3692)
- [x] [Hydra](https://netrunnerdb.com/en/card/22046) (#3707)
- [x] [Eavesdrop](https://netrunnerdb.com/en/card/22047) (#3708)
- [x] [Attitude Adjustment](https://netrunnerdb.com/en/card/22048) (#3741)
- [x] [Arella Salvatore](https://netrunnerdb.com/en/card/22049) (#3728)
- [x] [The Outfit: Family Owned and Operated](https://netrunnerdb.com/en/card/22050) (#3196) 
- [x] [Broad Daylight](https://netrunnerdb.com/en/card/22051) (#3672)
- [x] [Drudge Work](https://netrunnerdb.com/en/card/22052) (#3705)
- [x] [Blockchain](https://netrunnerdb.com/en/card/22053) (#3677)
- [x] [Formicary](https://netrunnerdb.com/en/card/22054) (#3731)
- [x] [Building Blocks](https://netrunnerdb.com/en/card/22055) (#3669)
- [x] [Too Big to Fail](https://netrunnerdb.com/en/card/22056) (#3152)
- [x] [Under the Bus](https://netrunnerdb.com/en/card/22057) (#3671)
- [x] [Lady Liberty](https://netrunnerdb.com/en/card/22058) (#3670)

**Comment by NoahTheDuke** [comment]
Too Big to Fail: #3152

**Comment by NoahTheDuke** [comment]
The Outfit: #3196

**Comment by NoahTheDuke** [comment]
Akiko Nisei: #3299

**Comment by NoahTheDuke** [comment]
Cradle: #3656

**Comment by NoahTheDuke** [comment]
Tycoon: #3657

**Comment by NoahTheDuke** [comment]
Mache: #3658

**Comment by presheaf** [comment]
I'll take Ika, Kyuban and Formicary.

**Comment by NoahTheDuke** [comment]
Game Changer: #3688 
Office Supplies: #3689

**Comment by Zeofar** [comment]
Saraswati Mnemonics: #3691

**Comment by nicohasa** [comment]
I can do Patchwork, District99, Thunder Art Gallery, Saraswati

**Comment by Zeofar** [comment]
Peeping Tom: #3692

**Comment by Saintis** [comment]
I can do Hydra and Drudge Work

**Comment by msbeck** [comment]
I'll take Eavesdrop, Attitude Adjustment, and ACME

**Comment by msbeck** [comment]
Rnr eavesdrop #3708

**Comment by NoahTheDuke** [comment]
Psych Mike: #3713

**Comment by NoahTheDuke** [comment]
Insight: #3660

**Comment by NoahTheDuke** [comment]
Gatekeeper: #3719

**Comment by NoahTheDuke** [comment]
Giordano Memorial Field: #3720

**Comment by msbeck** [comment]
RaR: Eavesdrop #3708

**Comment by NoahTheDuke** [comment]
I'll take Fast Break, Hangeki, and Otoroshi.

**Comment by NoahTheDuke** [comment]
Fast Break: #3730

**Comment by presheaf** [comment]
I can take Thimblerig.

**Comment by presheaf** [comment]
Thimblerig: #3738

**Comment by presheaf** [comment]
District 99: #3743 
SIU: #3742

**Comment by presheaf** [comment]
I think this issue can be closed. ;-;
