### ISSUE TITLE
Master Card Implementation Issue

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3253]
- [x] Down the White Nile: https://github.com/mtgred/netrunner/issues/3025
- [x] Council of the Crest https://github.com/mtgred/netrunner/issues/3096
- [x] The Devil and the Dragon https://github.com/mtgred/netrunner/issues/3219
- [x] Whispers in Nalubaale (#3348)
- [x] Kampala Ascendent https://github.com/mtgred/netrunner/issues/3273
- [x]  Reign and Reverie (#3184)

**Comment by NoahTheDuke** [comment]
rip in pepperonis, card implementation issue
