### ISSUE TITLE
Kampala Ascendent Card Implementations

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3273]
Rumored to be released ~June 2018?

Checked off means that the card is merged into master.
Place a link to the pull request next to the card when it is pushed.
If you wish to claim a card, make a comment on this issue or put your name next to the card.

- [x] Amina (https://github.com/mtgred/netrunner/pull/3288)
- [x] Better Citizen Program (#3331)
- [x] Black Hat (#3541)
- [x] Diversion of Funds (#3207)
- [x] Engolo (#3559)
- [x] False Flag (#3229)
- [x] Flame-Out (#3528)
- [x] High-Profile Target (#3226)
- [x] Hippo (#3527)
- [x] Kasi String (#3338)
- [x] Market Forces (#3231)
- [x] Mlinzi (#3524)
- [x] MTI Mwekundu (#3533)
- [x] Musaazi (#3557)
- [x] NEXT Diamond (#3526)
- [x] PAD Tap (#3563)
- [x] Reclaim (#3525)
- [x] Riot Suppression (#3564)
- [x] Surveyor (#3287)
- [x] Zer0 (#3405)

**Comment by msbeck** [comment]
If you want to work on any of the cards I put my name buy, PLEASE just let me know. Since the release is so far out, I thought I'd put my name in as placeholder for a variety of interesting or challenging cards that would take me around the engine to learn lots of new things.

**Comment by Saintis** [comment]
There should be some easy cards here for anyone who wants to start contributing.

**Comment by presheaf** [comment]
I'll take Black Hat.

**Comment by nicohasa** [comment]
I've made Zer0 #3405

**Comment by NoahTheDuke** [comment]
PAD Tap: #3563

**Comment by msbeck** [comment]
Another great achievement! Great job guys ^_^
