### ISSUE TITLE
Nisei Comprehensive Rules

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#3916]
On Monday, October 29th, Nisei released their Comprehensive Rules doc, which formalized and quantified a number of rules ambiguities that previously required UFAQ and developer commentary to handle. The changes look to be small where they exist, but we must update to handle them.

- [x] Clicks as resource (Director Haas doesn't make the corp gain clicks immediately, Victoria Jenkins doesn't make the runner lose clicks immediately, etc) (#3912)
- [x] Unification of "taking credits" and "gaining credits" to mean "gaining credits" (PAD Tap affected) (#3912)
- [ ] Checkpoints as specific moments to handle specific game-state changes
- [x] Cards entering the score area lose their names (Kasi String)
- [x] Players can no longer use prevent/avoid abilities to stop a cost from being paid
- [x] Players are no longer required to find a card when searching their deck
- [x] Cleaned up rules regarding consoles and regions, including specifications for non-upgrade regions
- [x] Revised the steps of installing and playing cards 
- [x] Errata Artist Colony to only find non-Events (we already did that one) (#3912)
- [x] Support new formats:
  - [x] Standard
  - [x] Eternal
  - [x] Core Experience
  - [x] Snapshot

**Comment by NoahTheDuke** [comment]
Don’t forget this, Noah. You can do all of these

**Comment by NoahTheDuke** [comment]
This is out of date now. Checkpoints are in the works, tho work is slow-going.
